<x-layouts::app :title="'Alta en curso'">
<div class="tfc-platform-page max-w-5xl space-y-7">
    <header class="tfc-page-heading"><div><p class="tfc-kicker">Alta en curso</p><h1 class="tfc-title">{{ trim($preRegistration->first_name.' '.$preRegistration->last_name) ?: 'Sin identificar' }}</h1><p class="tfc-subtitle"><span class="tfc-status">{{ $preRegistration->status->label() }}</span></p></div>@if ($preRegistration->status->value === 'draft')<a class="tfc-button" href="{{ route('pre-registrations.edit', $preRegistration) }}">Continuar alta →</a>@endif</header>
    <section class="tfc-card p-5 md:p-8"><h2 class="tfc-section-title">Cuestionario y circunstancias</h2>@if ($preRegistration->requiresReview())<p class="tfc-member-note mt-4">Esta alta requiere revisión del entrenador antes de continuar. No constituye un diagnóstico ni una autorización médica.</p><dl class="tfc-data-list mt-5">@foreach ($preRegistration->triggeringCircumstances() as $key => $value)<div><dt>{{ $key === 'pregnancy' ? 'Embarazo declarado' : 'Respuestas C-AAF afirmativas' }}</dt><dd>{{ is_array($value) ? implode(', ', array_keys($value)) : 'Sí' }}</dd></div>@endforeach</dl>@else<p class="mt-4 text-zinc-300">No hay circunstancias detonantes registradas.</p>@endif</section>
    @if ($preRegistration->status->value === 'requires_review' && $canReview)<section class="tfc-card p-5 md:p-8"><h2 class="tfc-section-title">Registrar revisión</h2><p class="tfc-subtitle">Registra la conversación y la decisión operativa. No uses términos de aptitud o autorización médica.</p><form method="POST" action="{{ route('pre-registrations.reviews.store', $preRegistration) }}" class="mt-6 space-y-4">@csrf<label class="tfc-field">Decisión<select name="decision" required><option value="can_continue">Puede continuar</option><option value="do_not_continue_for_now">No continuar por ahora</option></select></label><label class="tfc-field">Observaciones y aclaraciones de la conversación<textarea name="observations" required></textarea></label><button class="tfc-button">Guardar revisión →</button></form></section>@endif
    @if ($preRegistration->status->value === 'on_hold' && $canReview)<form method="POST" action="{{ route('pre-registrations.resume', $preRegistration) }}">@csrf<button class="tfc-button">Retomar para nueva revisión →</button></form>@endif
    <section class="tfc-card p-5 md:p-8"><h2 class="tfc-section-title">Historial de revisiones</h2><div class="mt-5 space-y-4">@forelse ($preRegistration->reviews as $review)<article class="border border-white/15 p-4"><p><strong>{{ $review->decision->label() }}</strong> · {{ $review->reviewed_at->format('d/m/Y H:i') }} · {{ $review->reviewedBy->name }}</p><p class="mt-2 text-zinc-300">{{ $review->observations }}</p><p class="mt-2 text-sm text-zinc-400">Circunstancias: {{ json_encode($review->triggering_circumstances, JSON_UNESCAPED_UNICODE) }}</p></article>@empty<p class="text-zinc-300">No hay revisiones registradas.</p>@endforelse</div></section>
</div>
</x-layouts::app>
