@php
    $activePlan = $member->trainingPlans->firstWhere('status', 'active');
    $planItems = old('items', $activePlan?->items?->map->only(['session_name', 'exercise', 'sets', 'repetitions', 'rest_seconds', 'intensity', 'notes'])->all() ?? [['session_name' => 'Sesión A']]);
@endphp
<section data-member-panel="entrenamiento" class="hidden" id="entrenamiento">
    <header class="tfc-panel-heading"><div><p class="tfc-kicker">Seguimiento deportivo</p><h2>Plan de entrenamiento</h2><p>Rutina vigente, responsable y ejercicios asignados.</p></div><span class="tfc-plan-state {{ $activePlan ? '' : 'tfc-plan-state--empty' }}">{{ $activePlan ? 'Plan activo' : 'Sin plan' }}</span></header>
    @if($activePlan)
        <article class="tfc-plan-overview"><div><span>Plan actual</span><strong>{{ $activePlan->title }}</strong><small>{{ $activePlan->objective ?: 'Sin objetivo específico' }}</small></div><dl><div><dt>Vigencia</dt><dd>{{ $activePlan->starts_on->format('d/m/Y') }} — {{ $activePlan->ends_on?->format('d/m/Y') ?? 'Sin fecha final' }}</dd></div><div><dt>Frecuencia</dt><dd>{{ $activePlan->sessions_per_week ? $activePlan->sessions_per_week.' sesiones/semana' : 'No indicada' }}</dd></div><div><dt>Entrenador</dt><dd>{{ $activePlan->assignedBy?->name ?? 'Usuario eliminado' }}</dd></div><div><dt>Actualizado</dt><dd>{{ $activePlan->updated_at->format('d/m/Y H:i') }}</dd></div></dl></article>
        <div class="tfc-workout-list">@foreach($activePlan->items->groupBy(fn($item) => $item->session_name ?: 'Rutina general') as $session => $items)<section class="tfc-workout-session"><h3>{{ $session }}</h3>@foreach($items as $item)<article><div><strong>{{ $item->exercise }}</strong>@if($item->notes)<small>{{ $item->notes }}</small>@endif</div><dl><div><dt>Series</dt><dd>{{ $item->sets ?: '—' }}</dd></div><div><dt>Repeticiones</dt><dd>{{ $item->repetitions ?: '—' }}</dd></div><div><dt>Descanso</dt><dd>{{ $item->rest_seconds !== null ? $item->rest_seconds.' s' : '—' }}</dd></div><div><dt>Intensidad</dt><dd>{{ $item->intensity ?: '—' }}</dd></div></dl></article>@endforeach</section>@endforeach</div>
        @if($activePlan->notes)<p class="tfc-member-note"><strong>Indicaciones:</strong><br>{{ $activePlan->notes }}</p>@endif
    @else<div class="tfc-empty-state"><strong>Aún no hay un plan asignado</strong><p>El entrenador puede crear la primera rutina desde esta ficha.</p></div>@endif
    @if($canManage)
        <details class="tfc-plan-editor" @if(old('_member_section') === 'entrenamiento') open @endif><summary>{{ $activePlan ? 'Editar plan actual' : 'Asignar primer plan' }}</summary>
            <form method="POST" action="{{ $activePlan ? route('members.training-plans.update', [$member, $activePlan]) : route('members.training-plans.store', $member) }}" class="tfc-form" data-training-plan-form>@csrf @if($activePlan) @method('PUT') @endif<input type="hidden" name="_member_section" value="entrenamiento">
                <div class="tfc-form-grid tfc-plan-fields"><label>Nombre del plan *<input name="title" value="{{ old('title', $activePlan?->title) }}" required maxlength="160"></label><label>Objetivo<textarea name="objective" maxlength="2000">{{ old('objective', $activePlan?->objective) }}</textarea></label><label>Inicio *<input type="date" name="starts_on" value="{{ old('starts_on', $activePlan?->starts_on?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" required></label><label>Final previsto<input type="date" name="ends_on" value="{{ old('ends_on', $activePlan?->ends_on?->format('Y-m-d')) }}"></label><label>Sesiones por semana<input type="number" name="sessions_per_week" min="1" max="14" value="{{ old('sessions_per_week', $activePlan?->sessions_per_week) }}"></label><label>Indicaciones generales<textarea name="notes" maxlength="5000">{{ old('notes', $activePlan?->notes) }}</textarea></label></div>
                <div class="tfc-exercise-editor-heading"><div><h3>Ejercicios</h3><p>Agrúpalos por sesión: A, B, movilidad…</p></div><button type="button" class="tfc-button tfc-button--small" data-add-exercise>Añadir ejercicio</button></div>
                <div class="tfc-exercise-editor" data-exercise-list>@foreach($planItems as $index => $item)<div class="tfc-exercise-row" data-exercise-row>@foreach(['session_name'=>'Sesión','exercise'=>'Ejercicio *','sets'=>'Series','repetitions'=>'Repeticiones / tiempo','rest_seconds'=>'Descanso (s)','intensity'=>'Intensidad','notes'=>'Notas'] as $name=>$label)<label class="{{ $name === 'exercise' ? 'tfc-exercise-name' : '' }}">{{ $label }}<input @if($name === 'rest_seconds') type="number" min="0" max="3600" @endif name="items[{{ $index }}][{{ $name }}]" data-name="{{ $name }}" value="{{ $item[$name] ?? '' }}" @required($name === 'exercise')></label>@endforeach<button type="button" class="tfc-remove-exercise" data-remove-exercise>Eliminar</button></div>@endforeach</div>
                <button class="tfc-button">{{ $activePlan ? 'Guardar cambios' : 'Asignar plan' }} →</button>
            </form>
            @if($activePlan)<form method="POST" action="{{ route('members.training-plans.archive', [$member, $activePlan]) }}" class="tfc-plan-archive" onsubmit="return confirm('¿Archivar este plan? El historial se conservará.')">@csrf<button class="tfc-text-button">Archivar plan actual</button></form>@endif
        </details>
    @endif
    @if($member->trainingPlans->where('status','archived')->isNotEmpty())<details class="tfc-plan-history"><summary>Planes anteriores ({{ $member->trainingPlans->where('status','archived')->count() }})</summary>@foreach($member->trainingPlans->where('status','archived') as $plan)<div><strong>{{ $plan->title }}</strong><span>{{ $plan->starts_on->format('d/m/Y') }} — {{ $plan->ends_on?->format('d/m/Y') ?? 'sin fecha final' }}</span></div>@endforeach</details>@endif
</section>
<template id="training-exercise-template"><div class="tfc-exercise-row" data-exercise-row>@foreach(['session_name'=>'Sesión','exercise'=>'Ejercicio *','sets'=>'Series','repetitions'=>'Repeticiones / tiempo','rest_seconds'=>'Descanso (s)','intensity'=>'Intensidad','notes'=>'Notas'] as $name=>$label)<label class="{{ $name === 'exercise' ? 'tfc-exercise-name' : '' }}">{{ $label }}<input @if($name === 'rest_seconds') type="number" min="0" max="3600" @endif data-name="{{ $name }}" @required($name === 'exercise')></label>@endforeach<button type="button" class="tfc-remove-exercise" data-remove-exercise>Eliminar</button></div></template>
