<x-layouts::app :title="'Editar pago'">
    <div class="tfc-platform-page tfc-narrow-page"><p class="tfc-kicker">Corrección auditada</p><h1 class="tfc-title">Editar pago</h1><p class="tfc-subtitle">Cualquier cambio queda registrado con tu usuario y la fecha de edición.</p>
        <form method="POST" action="{{ route('payments.update', $payment) }}" class="tfc-card tfc-form mt-8">@csrf @method('PUT')
            <div class="tfc-form-grid"><label>Sesiones compradas<input type="number" min="1" name="sessions_purchased" value="{{ old('sessions_purchased', $payment->sessions_purchased) }}" required></label><label>Importe (€)<input type="number" min="0" step="0.01" name="amount" value="{{ old('amount', $payment->amount) }}" required></label></div>
            <div class="tfc-form-grid"><label>Forma de pago<select name="payment_method" required>@foreach(['cash'=>'Efectivo','card'=>'Tarjeta','transfer'=>'Transferencia','bizum'=>'Bizum','other'=>'Otro'] as $value=>$label)<option value="{{ $value }}" @selected(old('payment_method', $payment->payment_method) === $value)>{{ $label }}</option>@endforeach</select></label><label>Referencia / detalle<input name="payment_method_detail" value="{{ old('payment_method_detail', $payment->payment_method_detail) }}" placeholder="Opcional"></label></div>
            <fieldset class="tfc-delivery-options"><legend>Vías para el justificante</legend>@foreach(['email'=>'Correo electrónico','whatsapp'=>'WhatsApp','print'=>'Impresión'] as $value=>$label)<label><input type="checkbox" name="delivery_methods[]" value="{{ $value }}" @checked(in_array($value, old('delivery_methods', $payment->delivery_methods ?? [])))> {{ $label }}</label>@endforeach</fieldset><label>Comentarios<textarea name="notes">{{ old('notes', $payment->notes) }}</textarea></label><button class="tfc-button">Guardar corrección →</button><a class="tfc-text-button" href="{{ route('payments.receipt', $payment) }}">Cancelar</a>
        </form>
    </div>
</x-layouts::app>
